# Generated by Django 2.2.9 on 2020-01-25 09:02

from django.db import migrations, models
import django.db.models.deletion
import page.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tel', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제품명')),
                ('photo', models.ImageField(blank=True, upload_to=page.utils.uuid_upload_to, verbose_name='제품 사진')),
                ('content', models.TextField(verbose_name='제품 설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('rest_quantity', models.PositiveIntegerField(verbose_name='남은 수량')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Customer', verbose_name='거래처')),
            ],
        ),
    ]
